<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="four_dof">

  
  <xacro:property name="link1_length" value="0.2" />
  <xacro:property name="link2_length" value="0.25" />
  <xacro:property name="link3_length" value="0.2" />
  <xacro:property name="link4_length" value="0.15" />
  
  <xacro:property name="link_radius" value="0.03" />
  
  <xacro:property name="joint_limit" value="3.14" />
  <xacro:property name="joint_lower_limit" value="-${joint_limit}" />
  <xacro:property name="joint_upper_limit" value="${joint_limit}" />


  <!-- Joint between chassis and first link -->
  <joint name="base_joint" type="revolute">
    <parent link="chassis"/>
    <child link="link1"/>
    <origin xyz="0 0 0.15" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="${joint_lower_limit}" upper="${joint_upper_limit}" effort="10" velocity="1"/>
  </joint>

  <!-- Link 1 -->
  <link name="link1">
    <visual>
      <geometry>
        <cylinder radius="${link_radius}" length="${link1_length}"/>
      </geometry>
      <material name="red">
        <color rgba="0.8 0 0 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${link_radius}" length="${link1_length}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="1"/>
      <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
    </inertial>
  </link>

  <!-- Joint between link1 and link2 -->
  <joint name="joint2" type="revolute">
    <parent link="link1"/>
    <child link="link2"/>
    <origin xyz="0 0 ${link1_length/2}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="${joint_lower_limit}" upper="${joint_upper_limit}" effort="10" velocity="1"/>
  </joint>

  <!-- Link 2 -->
  <link name="link2">
    <visual>
      <geometry>
        <cylinder radius="${link_radius}" length="${link2_length}"/>
      </geometry>
      <material name="green">
        <color rgba="0 0.8 0 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${link_radius}" length="${link2_length}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="1"/>
      <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
    </inertial>
  </link>

  <!-- Joint between link2 and link3 -->
  <joint name="joint3" type="revolute">
    <parent link="link2"/>
    <child link="link3"/>
    <origin xyz="0 0 ${link2_length/2}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="${joint_lower_limit}" upper="${joint_upper_limit}" effort="10" velocity="1"/>
  </joint>

  <!-- Link 3 -->
  <link name="link3">
    <visual>
      <geometry>
        <cylinder radius="${link_radius}" length="${link3_length}"/>
      </geometry>
      <material name="yellow">
        <color rgba="0.8 0.8 0 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${link_radius}" length="${link3_length}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="1"/>
      <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
    </inertial>
  </link>

  <!-- Joint between link3 and link4 -->
  <joint name="joint4" type="revolute">
    <parent link="link3"/>
    <child link="link4"/>
    <origin xyz="0 0 ${link3_length/2}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="${joint_lower_limit}" upper="${joint_upper_limit}" effort="10" velocity="1"/>
  </joint>

  <!-- Link 4 (End Effector) -->
  <link name="link4">
    <visual>
      <geometry>
        <cylinder radius="${link_radius}" length="${link4_length}"/>
      </geometry>
      <material name="white">
        <color rgba="1 1 1 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${link_radius}" length="${link4_length}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.5"/>
      <inertia ixx="0.005" ixy="0" ixz="0" iyy="0.005" iyz="0" izz="0.005"/>
    </inertial>
  </link>

  <!-- End Effector (optional) -->
  <link name="end_effector">
    <visual>
      <geometry>
        <sphere radius="0.02"/>
      </geometry>
      <material name="black">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
  </link>

  <joint name="end_effector_joint" type="fixed">
    <parent link="link4"/>
    <child link="end_effector"/>
    <origin xyz="0 0 ${link4_length/2}" rpy="0 0 0"/>
  </joint>

</robot>
